name: DIWT-AI X Pipeline
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # Semanal
jobs:
  test-and-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Pandoc
      run: sudo apt-get update && sudo apt-get install -y pandoc
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: python -m unittest autonomous_experiment_v4_4.py
    - name: Run pipeline
      run: python autonomous_experiment_v4_4.py --runs 1 --steps 50 --outdir experiments/run_ci --n-initial 5 --zenodo-token ${{ secrets.ZENODO_TOKEN }} --slack-token ${{ secrets.SLACK_TOKEN }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: experiment-results
        path: experiments/run_ci/
